export const EMPTY = {
  title: '',
  authors: [],
  status: 'unread',
  owned: false,
  previously_owned: false,
  shelf_id: null,
  building_id: null,
  room_id: null,
  unit_id: null,
  is_custom: false,
  fiction: null,
  source_type: '',
  rating: null,
  date_started: '',
  date_finished: '',
  language: 'English',
  original_language: '',
  translator: '',
  publisher: '',
  series: '',
  series_number: '',
  acquisition_source: '',
  acquisition_date: '',
  year_published: '',
  year_approximate: false,
  year_edition: '',
  isbn_10: '',
  isbn_13: '',
  asin: '',
  format: '',
  binding: '',
  condition: '',
  page_count: '',
  current_page: '',
  duration_minutes: '',
  narrators: [],
  description: '',
  notes: '',
  review: '',
  read_count: 0,
  tags: [],
  cover_path: null,
};

export const VIRTUAL_TAG_NAMES = ['Antique', 'Vintage', 'Translated', 'Re-read', 'Long', 'Short'];
